### PR TITLE
Upgrade Golang version to 1.13.8 and Kubernetes version to 1.15.9

### PR DESCRIPTION
**Pull request by Jeffwan**
1. Upgrade Dockerfile base image goland verison and travis CI golang version to 1.13.8
2. Migrate from Dep to go module
3. Upgrade Kubernetes dependencies to 1.15.9 and regenerate client and api codes
4. Upgrade code-gen scripts to use mod code-generator in GOPATH/pkg/mod and deprecate vendor folder

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/mxnet-operator/53)

### CODE REVIEW

**Comment by gaocegege** [comment]
Tests are failed, can you please fix it?

Thanks

**Comment by Jeffwan** [comment]
@gaocegege go linter problem, current library has been deprecated. I file a separate PR #56 to address this issue and copyright header to fix CI.  This PR will be updated later.

**Comment by Jeffwan** [comment]
I have a follow up PR to delete `vendor` folder. I want to make this PR clear and easy to review.

**Comment by wackxu** [comment]
Thanks for your contribution.
/lgtm
/approve

**Pull request merged**
