### PR TITLE
add travis.yml to mxnet-operator

### PR DESCRIPTION
**Pull request by wackxu**
@suleisl2000 @gaocegege

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/mxnet-operator/37)

### CODE REVIEW

**Comment by wackxu** [comment]
I am fixing some CI error

**Comment by wackxu** [comment]
image
@gaocegege @suleisl2000 Have you ever seen this error? Do we need some config on https://coveralls.io

**Comment by wackxu** [comment]
@jlewi @ abhi-g @gaocegege Could you help configure mxnet-operator repo on https://coveralls.io?

**Comment by gaocegege** [comment]
We need @jlewi 's help

**Comment by wackxu** [comment]
@google-team@kubeflow.org We need help to configure the repo.

**Comment by wackxu** [comment]
@jlewi @johnugeorge Could your take a look at this.

**Comment by gaocegege** [comment]
I asked @jlewi in slack but no response. Please wait.

**Comment by wackxu** [comment]
/hold
@gaocegege ok, Could you invite me to the kubeflow slack?

**Comment by gaocegege** [comment]
@wackxu We have a public link for slack: https://join.slack.com/t/kubeflow/shared_invite/enQtNDg5MTM4NTQyNjczLWUyZGI1ZmExZWExYWY4YzlkOWI4NjljNjJhZjhjMjEwNGFjNmVkNjg2NTg4M2I0ZTM5NDExZWI5YTIyMzVmNzM

**Comment by wackxu** [comment]
@gaocegege Got it, thanks

**Comment by johnugeorge** [comment]
Jeremy will be busy with Kubecon this week

**Comment by richardsliu** [comment]
@gaocegege @wackxu I enabled coveralls, it should work now.

**Comment by wackxu** [comment]
@gaocegege @suleisl2000 We can merge this now

**Comment by gaocegege** [comment]
@wackxu Maybe you could be a member of the org, then the test will be triggered automatically.

**Comment by wackxu** [comment]
@gaocegege I have apply to be member in the https://github.com/kubeflow/internal-acls repo and that was merged. Anything else needs to be done  to be a member?

**Comment by gaocegege** [comment]
@wackxu You could ask for help if you are not invited in the next 2 weeks.

**Comment by wackxu** [comment]
@gaocegege Got it, thanks very much.

**Pull request merged**
