### PR TITLE
Migrate controller implementation to kubeflow/common fashion

### PR DESCRIPTION
**Pull request by Jeffwan**
Major changes include 

1. Bump Kubernetes dependency version to 1.16.9
2. Simplify v1 APIs by leverage common types in `kubeflow/common/pkg/apis/common/v1`
3. Replace exiting implementation with `kubeflow/common/pkg/controller.v1/common` and get ride of `tf-operator/pkg/common/jobcontroller`
4. Replace batch scheduler from `kube-batch` to `volcano` (this is alone with kubeflow common upgrade)
5. Remove `MXReplicaSpec.Label` and use `replica.PodTemplate.Annotation[mxJobTunerServerKey]` instead. This is used for tvm auto-tuning.

### CODE REVIEW

**Comment by terrytangyuan** [comment]
Thanks! This has a lot of breaking changes. Do you mind if I cut a release before merging this since I believe there are users of this operator? If so, do you have any suggested version number in mind?

**Comment by Jeffwan** [comment]
/hold

This is for review only. 

@terrytangyuan Sure. Can you help cut a 0.7.0 release on commit https://github.com/kubeflow/mxnet-operator/commit/9f050f82308aef63fe5403b68cdd8605e99e1696? 

This is a stable version last year. I will leave this year's change to future release.

**Comment by Jeffwan** [comment]
coverage drops a little bit. Have to add `defaults_test.go` to improve coverage

**Comment by terrytangyuan** [comment]
> @terrytangyuan Sure. Can you help cut a 0.7.0 release on commit [9f050f8](https://github.com/kubeflow/mxnet-operator/commit/9f050f82308aef63fe5403b68cdd8605e99e1696)? This matches with last years' Kubeflow release version.
> 
> This is a stable version last year. I will leave this year's change to future release.

Done. I just cut a release for v0.7.0: https://github.com/kubeflow/mxnet-operator/releases/tag/v0.7.0

**Comment by Jeffwan** [comment]
I will wait to the weekend to see anyone else has more concerns

**Pull request merged**
