### PR TITLE
OWNERS: Fix a typo

### PR DESCRIPTION
**Pull request by gaocegege**
Sorry for the typo

Signed-off-by: Ce Gao <gaoce@caicloud.io>

---
This change is [Reviewable](https://reviewable.io/reviews/kubeflow/mxnet-operator/4)

### CODE REVIEW

**Comment by gaocegege** [comment]
@jlewi Sorry, maybe we need your help to fix the format of OWNERS again

**Comment by jlewi** [comment]
/lgtm
/approve

Manually merging to fix OWNERs

**Pull request merged**
