### PR TITLE
Add initial list of adopters

### PR DESCRIPTION
**Pull request by terrytangyuan**
This is just an initial list of adopters. **If your company uses MXNet Operator, please let us know here.** This would help us gather use cases and collaborate with other organizations and open source communities. 

Signed-off-by: terrytangyuan <terrytangyuan@gmail.com>

### CODE REVIEW

**Comment by Jeffwan** [comment]
/lgtm

Looks good to me on my side

**Comment by terrytangyuan** [comment]
Merging this for now since we have already gathered an initial list. If others want to be added, please send a pull request. Thanks.

**Pull request merged**
