### PR TITLE
MXNet Operator: Move manifests development upstream

### PR DESCRIPTION
**Pull request by yanniszark**
### Issue Resolved

Resolves: https://github.com/kubeflow/mxnet-operator/issues/88
Umbrella issue: https://github.com/kubeflow/manifests/issues/1740

### Description

As part of the work of wg-manifests for 1.3
(https://github.com/kubeflow/manifests/issues/1735), we are moving manifests
development in upstream repos. This gives the application developers full
ownership of their manifests, tracked in a single place.

This PR copies the manifests for application `MXNet Operator`
from path `apps/mxnet-job/upstream` of kubeflow/manifests to path
`manifests` of the upstream repo (https://github.com/kubeflow/mxnet-operator).

cc @kubeflow/wg-training-leads

### CODE REVIEW

**Comment by yanniszark** [comment]
@kubeflow/wg-training-leads the build is failing, which I believe is caused by coveralls.
This PR doesn't change any go files. Why does this happen?
Could you please take a look? Was the CI in a broken state?

**Review by terrytangyuan — APPROVED** [review]
Others PTAL

/lgtm

**Comment by yanniszark** [comment]
@kubeflow/wg-training-leads kind ping.
Could you please take a look at the CI?
The build is failing, which I believe is caused by coveralls.
This PR doesn't change any go files. Why does this happen?
Could you please take a look? Was the CI in a broken state?

**Comment by terrytangyuan** [comment]
I think it's because some of the generated code needs to be updated since the year just went from 2020 to 2021. You can run `hack/verify-codegen.sh` to reproduce and fix locally.

**Comment by yanniszark** [comment]
@terrytangyuan thanks for the pointers! I ran the update-codegen script and `hack/verify-codegen.sh` produces no errors on my machine. However, it errors out in the CI. Could you take a look? I'm kinda perplexed by this situation.

**Comment by yanniszark** [comment]
kind ping @terrytangyuan @kubeflow/wg-training-leads

**Comment by terrytangyuan** [comment]
Looks like you might have forgotten to commit/push some of the files? I am seeing the following in the CI:
```
>> Removing /tmp/tmp.LmGH2e9llP

diffing hack/../pkg against freshly generated codegen

diff -Naupr hack/../pkg/apis/mxnet/v1/zz_generated.defaults.go hack/../_tmp/pkg/apis/mxnet/v1/zz_generated.defaults.go

--- hack/../pkg/apis/mxnet/v1/zz_generated.defaults.go	2021-03-01 20:25:56.281063467 +0000

+++ hack/../_tmp/pkg/apis/mxnet/v1/zz_generated.defaults.go	2021-03-01 20:24:10.000000000 +0000

@@ -1,6 +1,6 @@

 // +build !ignore_autogenerated

 

-// Copyright 2021 The Kubeflow Authors

+// Copyright 2020 The Kubeflow Authors

 //

 // Licensed under the Apache License, Version 2.0 (the "License");

 // you may not use this file except in compliance with the License.

diff -Naupr hack/../pkg/apis/mxnet/v1beta1/zz_generated.defaults.go hack/../_tmp/pkg/apis/mxnet/v1beta1/zz_generated.defaults.go

--- hack/../pkg/apis/mxnet/v1beta1/zz_generated.defaults.go	2021-03-01 20:25:48.537063467 +0000

+++ hack/../_tmp/pkg/apis/mxnet/v1beta1/zz_generated.defaults.go	2021-03-01 20:24:10.000000000 +0000

@@ -1,6 +1,6 @@

 // +build !ignore_autogenerated

 

-// Copyright 2021 The Kubeflow Authors

+// Copyright 2020 The Kubeflow Authors

 //

 // Licensed under the Apache License, Version 2.0 (the "License");

 // you may not use this file except in compliance with the License.

hack/../pkg is out of date. Please run hack/update-codegen.sh
```
Perhaps try committing those diff or manually pick them up if necessary.

**Comment by yanniszark** [comment]
@terrytangyuan thanks, I ran the command inside a Go 1.13 container and that seems to do the trick.
However, now I get a mysterious error from coveralls. It says that coverage has dropped because of this PR. However, I don't see how that can be, since I only added comments to go files (autogeneration).
Could you please take a look? Also cc @Jeffwan

**Review by terrytangyuan — APPROVED** [review]

**Pull request merged**
